defaults:
  - datamodule: lidc_idri_config
  - model: unet3D_config
exp_name: "Softmax"
version: "test"
data_input_dir: "/home/jloch/Desktop/diff/luzern/values_datasets/lidc"
save_dir: "/home/jloch/Desktop/diff/luzern/values/uncertainty_modeling/saves"
seed: 123
max_epochs: 150
batch_size: 8
learning_rate: 3.0e-4
weight_decay: 10.0e-6

optimizer:
  _target_: torch.optim.RMSprop
  lr: ${learning_rate}
  weight_decay: ${weight_decay}
  momentum: 0.6
lr_scheduler:
  _target_: torch.optim.lr_scheduler.PolynomialLR
  power: 0.9
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${save_dir}
  name: ${exp_name}
progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 10
trainer:
  max_epochs: 300
  accelerator: gpu
  devices: 1
  precision: 16-mixed