#@package _global_
defaults:
  - /../../uncertainty_modeling/configs/data/chaksu128
  - _self_

data_input_dir: "/home/jloch/Desktop/diff/luzern/values_datasets/chaksu128"
datamodule_config: ${data}
data:
  data_input_dir: ${data_input_dir}
base_splits_path: "/home/jloch/Desktop/diff/luzern/values_datasets/chaksu128/splits"
experiments:
  - ${SWEEP_ALL}
  - ${SWEEP_NONE}
  - ${TTA_TESTS}
  - ${EXTRACT_SOFTMAX}

DROPOUT_SSN:
  iter_params:
    shift: [ "scanner" ]
    pred_model: ["ssn"]
    seed: [ "120" ]
    seed1: ["0"]
    eu: ["dropout"]
    cfg: [ "standard" ]
    data: [ "chaksu128" ]
  exp_name: "chaksu128"
  naming_scheme_version: "{pred_model}_{eu}_{seed1}/e500_ema"
  aggregations: [ "all" ]
  fold: 0
  rank: 5
  image_ending: ".png"
  unc_ending: ".tif"
  n_reference_segs: 5
  only_pu: false
  evaluate_training_data: ${evaluate_training_data}

EXTRACT_DROPOUT:
  iter_params:
    shift: [ "scanner" ]
    pred_model: ["dropout"]
    seed: [ "120" ]
    cfg: [ "standard" ]
    name: ["s0.3_mi0.1","s0.5_mi0.2","s1.0_mi0.5","s3.0_mi1.0","s5.0_mi2.0","s10.0_mi4.0"]
    data: [ "chaksu128" ]
  skip_finished: false
  exp_name: "extract_chaksu"
  naming_scheme_version: "{pred_model}10_{name}_olap/e320_ema"
  aggregations: [ "all" ]
  fold: 0
  rank: 5
  image_ending: ".png"
  unc_ending: ".tif"
  n_reference_segs: 5
  only_pu: false
  evaluate_training_data: ${evaluate_training_data}

EXTRACT_SOFTMAX:
  iter_params:
    shift: [ "scanner" ]
    pred_model: ["softmax"]
    seed: [ "120" ]
    cfg: [ "standard" ]
    #name: ["s0.3_mi0.1","s0.5_mi0.2","s1.0_mi0.5","s3.0_mi1.0","s5.0_mi2.0","s10.0_mi4.0"]
    #name: ['s20.0_mi4.0', 's10.0_mi8.0', 's20.0_mi8.0']
    #name: ["0.1_s10.0_mi4.0","0.1_s10.0_mi8.0","0.1_s10.0_mi12.0","0.1_s10.0_mi16.0","0.1_s10.0_mi20.0","0.1_s10.0_mi30.0","0.1_s1.0_mi8.0","0.1_s2.0_mi8.0","0.1_s3.0_mi8.0","0.1_s5.0_mi8.0","0.1_s10.0_mi8.0","0.1_s15.0_mi8.0","0.1_s20.0_mi8.0","0.03_s10.0_mi8.0","0.04_s10.0_mi8.0","0.05_s10.0_mi8.0","0.06_s10.0_mi8.0","0.08_s10.0_mi8.0","0.1_s10.0_mi8.0","0.12_s10.0_mi8.0","0.15_s10.0_mi8.0"]
    name: ["0.04_s10.0_mi4.0","0.04_s10.0_mi8.0","0.04_s10.0_mi12.0","0.04_s10.0_mi16.0","0.04_s10.0_mi20.0","0.04_s10.0_mi30.0","0.04_s1.0_mi8.0","0.04_s2.0_mi8.0","0.04_s3.0_mi8.0","0.04_s5.0_mi8.0","0.04_s15.0_mi8.0","0.04_s20.0_mi8.0","0.025_s10.0_mi8.0","0.03_s10.0_mi8.0","0.035_s10.0_mi8.0","0.045_s10.0_mi8.0","0.05_s10.0_mi8.0","0.055_s10.0_mi8.0"]
    data: [ "chaksu128" ]
  skip_finished: false
  exp_name: "extract_chaksu"
  naming_scheme_version: "{pred_model}10_frac{name}_olap/e500_ema"
  aggregations: [ "all" ]
  fold: 0
  rank: 5
  image_ending: ".png"
  unc_ending: ".tif"
  n_reference_segs: 5
  only_pu: false
  evaluate_training_data: ${evaluate_training_data}

TTA_TESTS:
  iter_params:
    shift: [ "scanner" ]
    pred_model: ["softmax"]
    seed: [ "120" ]
    cfg: [ "standard" ]
    aug: [ "no_aug" , "weak_aug", "strong_aug" ]
    aug_tta: ["strong", "weak", "strong"]
    data: [ "chaksu128" ]
    eu: ["dropout", "swag_diag", "swag"] 
  skip_finished: false
  exp_name: "tta_tests"
  naming_scheme_version: "chaksu_{aug}_{eu}_tta_{aug_tta}/e320_ema"
  aggregations: [ "all" ]
  fold: 0
  rank: 5
  image_ending: ".png"
  unc_ending: ".tif"
  n_reference_segs: 5
  only_pu: false
  evaluate_training_data: ${evaluate_training_data}

DROPOUT_CHAKSU_SWEEP:
  iter_params:
    shift: [ "scanner" ]
    pred_model: ["softmax"]
    seed: [ "120" ]
    #name: [ "locsweep_dec_r0.2", "ratesweep_r0.7", "locsweep_all+skip+res_r0.2", "ratesweep_r0.8", "ratesweep_r0.6", "ratesweep_r0.5", "ratesweep_r0.2", "ratesweep_r0.4", "ratesweep_r0.05", "locsweep_enc+skip_r0.2", "ratesweep_r0.1", "locsweep_enc_r0.2", "locsweep_all+res_r0.2", "ratesweep_r0.3", "locsweep_mid+skip_r0.2", "ratesweep_r0.9", "locsweep_enc+skip+res_r0.2", "locsweep_all+skip_r0.2", "locsweep_all_r0.2", "locsweep_mid_r0.2" ]
    #name: ["locsweep_all_pb_r0.4", "locsweep_enc+skip_r0.4", "locsweep_enc_r0.4", "locsweep_encmid+skip_r0.4", "locsweep_encmid_r0.4", "locsweep_enc+skip_pb_r0.4", "locsweep_enc_pb_r0.4", "locsweep_encmid+skip_pb_r0.4", "locsweep_encmid_pb_r0.4" ]
    name: ["subens_opt_encskip_n10s10", "subens_opt_encmid_n10s10", "subens_opt_all_n10s10"]
    cfg: [ "standard" ]
    data: [ "chaksu128" ]
  skip_finished: true
  exp_name: "dropout_chaksu_sweep"
  naming_scheme_version: "{name}/e320_ema"
  aggregations: [ "all" ]
  fold: 0
  rank: 5
  image_ending: ".png"
  unc_ending: ".tif"
  n_reference_segs: 5
  only_pu: false
  evaluate_training_data: ${evaluate_training_data}

SUBENS:
  iter_params:
    shift: [ "scanner" ]
    pred_model: ["softmax"]
    seed: [ "120" ]
    s: [ "1" ]
    n: [ "0.35", "0.5" ]
    cfg: [ "standard" ]
    data: [ "chaksu128" ]
  exp_name: "chaksu128"
  naming_scheme_version: "{pred_model}_subens_00_n{n}s{s}/e500_ema"
  aggregations: [ "all" ]
  fold: 0
  rank: 5
  image_ending: ".png"
  unc_ending: ".tif"
  n_reference_segs: 5
  only_pu: false
  evaluate_training_data: ${evaluate_training_data}

DROPOUT_SWEEP:
  iter_params:
    shift: [ "scanner" ]
    pred_model: ["softmax"]
    seed: [ "120" ]
    seed1: [ "0", "1", "2", "3", "4" ]
    d_rate: [ "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.8", "0.9" ]
    eu: ["dropout"]
    cfg: [ "standard" ]
    data: [ "chaksu128" ]
  exp_name: "chaksu128_dropoutsweep"
  naming_scheme_version: "{pred_model}_{eu}_{d_rate}/e500_ema"
  aggregations: [ "all" ]
  fold: 0
  rank: 5
  image_ending: ".png"
  unc_ending: ".tif"
  n_reference_segs: 5
  only_pu: false
  evaluate_training_data: ${evaluate_training_data}


SWEEP_NONE:
  iter_params:
    shift: [ "scanner" ]
    pred_model: ["prob_unet", "diffusion", "ssn"]
    seed: [ "120" ]
    seed1: [ "0", "1", "2", "3", "4" ]
    eu: ["none"]
    cfg: [ "standard" ]
    data: [ "chaksu128" ]
  exp_name: "chaksu128"
  naming_scheme_version: "{pred_model}_{eu}_{seed1}/e500_ema"
  aggregations: [ "all" ]
  fold: 0
  rank: 5
  image_ending: ".png"
  unc_ending: ".tif"
  n_reference_segs: 5
  only_pu: false
  evaluate_training_data: ${evaluate_training_data}


SWEEP_ALL:
  iter_params:
    shift: [ "scanner" ]
    pred_model: ["prob_unet", "diffusion", "ssn", "softmax"]
    seed: [ "120" ]
    seed1: [ "0", "1", "2", "3", "4" ]
    eu: ["ensemble", "swag_diag", "swag", "dropout"]
    cfg: [ "standard" ]
    data: [ "chaksu128" ]
  exp_name: "chaksu128"
  naming_scheme_version: "{pred_model}_{eu}_{seed1}/e500_ema"
  aggregations: [ "all" ]
  fold: 0
  rank: 5
  image_ending: ".png"
  unc_ending: ".tif"
  n_reference_segs: 5
  only_pu: false
  evaluate_training_data: ${evaluate_training_data}
